<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-02-15T06:49:17+01:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.name
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'WaniKani Classroom',
            'seo' => [
                'canonical_url' => '',
                'canonical_ssl_url' => '',
            ],
        ],
    ],
];
